name: LengMOTD
version: 1.0.0
main: org.leng.LengMOTD
api-version: 1.20
description: A plugin to display a random one-line in the server MOTD.
commands:
  lmotd:
    description: LengMOTD 主命令
    usage: /<command> reload | wh
permissions:
  lmotd.reload:
    description: 允许重载配置文件
    default: op
  lmotd.wh:
    description: 允许切换维护模式
    default: op