# 配置文件
mode: online  # 可选值：online (从一言接口获取) 或 custom (自定义内容)
online:
  first: "§6欢迎来玩我的服务器呀"  # 第一行内容
  second: "§3★★★ #此处自动替换成一言 ★★★"  # 第二行内容，前面可以加颜色代码

custom:
  first:
    - "§2欢迎来玩我的服务器丫"
    - "§7这是一个测试服务器"
  second:
    - "§a这是第二行内容"
    - "§b这是另一个第二行内容"
  third:
    - "§c这是第三行内容"
    - "§d这是另一个第三行内容"

maintenance_mode: false  # 是否开启维护模式
maintenance_message: "§c服务器正在维护中，请稍后再试！"  # 维护模式时显示的消息
icon: "icon/icon.png"  # 图标路径，必须放在插件的 icon 文件夹中

staff: []  # 可以在维护模式下加入服务器的玩家名单